# Generated by Django 5.1.7 on 2025-03-07 01:52

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='order',
            field=courses.fields.OrderField(blank=True, default=0),
        ),
    ]
