# Generated by Django 5.1.7 on 2025-03-07 01:53

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=courses.fields.OrderField(blank=True, default=0),
        ),
    ]
