# Generated by Django 5.1.7 on 2025-03-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_order_alter_module_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='xfile',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
    ]
